### PR TITLE
Associations' project

### PR DESCRIPTION
**Pull request by lucasmazo32**
Instructions are more descriptive in the README file.

As always, before running the programme run:

- bundle update
- bundle
- rails db:drop
- rails db:create
- rails db:migrate
- rails db:seed

Afterwards, start the server.

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @lucasmazo32 @rkyankya  , 👋 You have done a great job in this project 👏 

* [x]  No debugging instructions in commited code (as discussed [here](https://questions.microverse.org/t/debugging-instructions-code/346)) (screenshot from [Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/debugging_requirement.png))

image
#### Event controller `#create`
* [x] uses `#build` method on association, i.e. current_user.events.build(event_params) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

#### `#index`
* [x] lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

* [x]  lists ucomping events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

#### UsersController

#### `show` action


* [x] lists events created by user, i.e.` @created_events =  current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

* [x] lists events previoulsy attendented by user using event model scope, i.e. `@past_events = current_user.attended_events.previous ` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

 lists upcoming events previously attended by user using event model scope, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

#### Tests


 * [x] models should have unit tests for associations (Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [x]  authentication have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

 * [x] event managment features have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] automated tests are failing
image

----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack _

**Comment by lucasmazo32** [comment]
Made the necessary corrections in some of the cases except:

- For the user's controller, I used methods to do so (when we add the optional advanced feature from the Odin project I can not continue with active record).

For your automated test failings:
- I already list all the events. Filling the form creates an event. Visiting the Event show display the list of attendees (in case there is one, otherwise it will not display anything), and it displays the creator of the event.
- Filling the form creates a User. It shows all the events the user has created in the user's home page. The other test will almost all the time fail because of Odin's additional feature, that's why I have an invited category. 
- I deleted the methods when I use the scope for events.
- I have methods (or scopes) for the user's future events and attended/created events They are in the InvitationsHelper.

**Comment by lucasmazo32** [comment]
BTW, the additional feature in the Odin project is:

Users can invite other users to their event. Only invited users can attend an event. That's why I created a new column in the table invitations which is "Accepted", it tells me if the user in fact decided to go to an event. Of course, the default is false.

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @lucasmazo32 @rkyankya  , 👋 You have done a great job in this project 👏 
* [ ] [Optional] getting error while inviting, for reference 

image




----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Pull request merged**
